name: Go CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'image-action-gh/base-project/image-scan/**'
jobs:
  test-build-publish:
    name: Test, Build, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>1.21' # Set this to the Go version you want to use
       
      - name: Install dependencies
        working-directory: image-action-gh/base-project/image-scan
        run:  go mod tidy

      - name: Test
        working-directory: image-action-gh/base-project/image-scan
        run: go test ./...

      - name: Build
        working-directory: image-action-gh/base-project/image-scan
        run: go build -o image-scan
